version: '3.9'
services:
  db:
    image: postgres:16
    container_name: loanapp-db
    restart: always
    environment:
      POSTGRES_DB: loanapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
