spring:
  profiles:
    active: ${ENV_PROFILE:dev}

  application:
    name: LoanAppBackend
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false