spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loanapp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: the-strongest-word-from-dev-test-of-integration-with-64-bytes-for-HS512
  expiration-ms: 10800000