spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loanapp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-7v8qmxq2rcmv3w7w.us.auth0.com/.well-known/jwks.json
          issuer-uri: https://dev-7v8qmxq2rcmv3w7w.us.auth0.com/

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE