spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://${AUTH0_DOMAIN}/.well-known/jwks.json
          issuer-uri: https://${AUTH0_DOMAIN}/


logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate.SQL: ERROR
    com.LoanAppBackend: INFO