name: Auto PR Description (OpenAI)

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate-pr-description:
    name: Generate PR Description via OpenAI
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Collect commit messages
        id: collect
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          COMMITS=$(gh api repos/${{ github.repository }}/pulls/$PR_NUMBER/commits --jq '.[].commit.message' | sed 's/^/- /')
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Generate PR description with OpenAI
        id: openai
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          PROMPT=$(cat << 'EOF'
          You are an assistant that writes concise, professional GitHub Pull Request descriptions.
          Summarize the following commits in markdown with clear sections:
          - **Summary:** short overview
          - **Details:** bullet points for technical work
          - **Impact:** mention affected modules, risks, or backward compatibility
          EOF
          )

          BODY=$(curl -s -X POST "https://api.openai.com/v1/chat/completions" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-4o-mini",
              "messages": [
                {"role": "system", "content": "'"$PROMPT"'"},
                {"role": "user", "content": "Commits:\n'"${{ steps.collect.outputs.commits }}"'"}
              ],
              "temperature": 0.4
            }' | jq -r '.choices[0].message.content')

          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update PR description
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
            -X PATCH \
            -f body="${{ steps.openai.outputs.body }}"
