name: Validate Commit Messages

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  commits:
    name: Validate commit messages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.yml
